### ISSUE TITLE
Extra sorteringen

### ISSUE THREAD

**Issue by bluediamond1984** [marcvanbreemen/gilde_vlierden_app_discussie#8]
Extra sorteringen zijn gewenst:

`Aanwezig` waarbij de geaccepteerden bovenaan staan, gesorteerd op nummer van klein naar groot. Daaronder de aanwezigen, gesorteerd op nummer van klein naar groot. Overigen statussen hoeven niet zichtbaar te zijn; Hierdoor kan in 1 overzicht bekeken worden hoeveel verkopers er nog moeten gaan komen.

`Betaald` waarbij diegene die nog betalen moeten bovenaan staan, gesorteerd op nummer van klein naar groot. Daaronder diegene die al betaald hebben, gesorteerd op nummer van klein naar groot.

**Comment by marcvanbreemen** [comment]
Ik heb hier een filter functionaliteit van gemaakt.

<img width="326" alt="Scherm­afbeelding 2024-04-01 om 12 54 05" src="https://github.com/marcvanbreemen/gilde_vlierden_app_discussie/assets/53403644/6a13a6a5-70ea-4682-9a69-a77110c38da7">

**Comment by bluediamond1984** [comment]
Ziet er goed uit 👍

**Comment by bluediamond1984** [comment]
De functie van `Toon positie` heeft meer toegevoegde waarde als het filter omgekeerd werkt. Nu worden de verkopers met een posities weg gelaten, maar je wilt graag alleen de lijst zien van diegene die een positie hebben toegewezen gekregen. Dat is vooral voor het plaatsen van de voertuigen gemakkelijk.
Dus dat je alleen de verkopers ziet die een positie toegewezen hebben gekregen.
