### ISSUE TITLE
Visuele weergave van icoontjes

### ISSUE THREAD

**Issue by bluediamond1984** [marcvanbreemen/gilde_vlierden_app_discussie#9]
Kunnen de icoontjes op de onderste rij binnen het kader van het nummer altijd op dezelfde plek staan? Dan is in 1 opslag sneller zichtbaar wie bijvoorbeeld betaald hebben.

**Comment by marcvanbreemen** [comment]
In verkoperslijst zijn de indicator iconen nu altijd zichtbaar en altijd op dezelfde positie. Indien uit hebben ze een lichtgrijze kleur en anders, per soort indicator, een eigen kleur. 

![image](https://github.com/marcvanbreemen/gilde_vlierden_app_discussie/assets/53403644/ff4b4843-214f-41d2-9c84-27a9c420d4be)
